### PR TITLE
Persisting current state and history states of super states

### PR DESCRIPTION
**Pull request by ursenzler**
Allows to save and load internal state of the state machine (current state, history states).

The state machine has still to be defined (In, On, DefineHierarchy, ...) but instead of Initialize, Load can be used to reset a prior internal state.

### CODE REVIEW

**Comment by danielmarbach** [comment]
Mental note to myself:
- [ ] that all other projects that use fakeiteasy are also upgraded to 1.8

**Comment by danielmarbach** [comment]
For symmetrical reasons I would name the loader methods LoadXxx because the Saver methods are called SaveXxx

**Comment by danielmarbach** [comment]
What about:

 danielmarbach commented 10 hours ago 
For symmetrical reasons I would name the loader methods LoadXxx because the Saver methods are called SaveXxx

**Comment by ursenzler** [comment]
Hmm, must have overlook it :-(

**Comment by ursenzler** [comment]
Renamed and pushed

**Comment by danielmarbach** [comment]
Last point: do we need to mark the state objects serializable?

**Comment by ursenzler** [comment]
PCL does not know the Serializable attribute :-(

**Pull request merged**
